### ISSUE TITLE
Cosmonium on macOS

### ISSUE THREAD

**Issue by malefika84** [cosmonium/cosmonium#10]
Hello

why Cosmonium on macOS asks for keyboard permission from other apps? If denied, software fails to open

**Comment by el-dee** [comment]
Permissions on macOS have changed with macOS Catalina, and the underlying 3D engine, Panda3D, is using a deprecated input API which now requires this extended permission.

It has been solved in the latest versions of Panda3D, and it will be fixed when a new release of Cosmonium will be done. Naively, I thought I would make a release shortly afterwards but I kept adding new features and bugfixes, delaying the new release. I hope it will be ready near the end of this month!

**Comment by malefika84** [comment]
That's good. Thanks a lot for explanation.

**Comment by el-dee** [comment]
Forgot to update this, the fix is now included in the dev builds :  https://github.com/cosmonium/cosmonium/wiki/Download#development-builds
