### ISSUE TITLE
Incorrect cel:// urls in wiki

### ISSUE THREAD

**Issue by 375gnu** [cosmonium/cosmonium#12]
At least some of them:
incorrect position, looks like observer is between Pan and Saturn:
cel://Follow/Sun:Saturn:Pan/2019-09-24T01:26:11.75726?x=hd+WcfE8/////////////w&y=78R92Y9s&z=vSGwz0QwAw&ow=0.996460612057&ox=0.0030448977001&oy=0.0752197931511&oz=-0.0374026728395&track=Sun:Saturn&select=Sun:Saturn&fov=40.0&ts=100.0&ltd=0&p=1&rf=3973015&lm=0&tsrc=0&ver=3

absolutely incorrect, that time Sun, Io and Saturn have different mutual posiotion
cel://Follow/Sun:Jupiter:Io/2019-09-23T10:18:38.06264?x=RItPN31UMA&y=wxPTFQUWAQ&z=xak8Yf1a8P///////////w&ow=0.674232671672&ox=-0.00662098326889&oy=-0.738475574579&oz=-0.0045047510651&select=Sun:Jupiter:Io&fov=40.0&ts=100.0&ltd=0&p=1&rf=3973015&lm=0&tsrc=0&ver=3

There were no Sun eclipse that time:
cel://Follow/Sun:Earth/2019-07-31T13:47:41.29865?x=8NJT8+vOd////////////w&y=aG5aeBA&z=iC7alUUQUv///////////w&ow=0.32329377232&ox=0.12310192209&oy=0.937296222843&oz=-0.0424599128764&select=Sun:Earth&fov=40.0&ts=500.0&ltd=0&p=1&rf=3973015&lm=0&tsrc=0&ver=3

I tested them in Celestia 1.6.2

**Comment by el-dee** [comment]
First of all, I should apologize, I though I had written an explanation about the bug, but it's obviously not the case !

When the screenshots and URL were taken, the app was still using mean orbital elements and rotation models. It was good enough to have a rough representation of the solar system and test the rendering, but obviously this has as consequences completely wrong transit and eclipses !

I just released a new version of the engine which (amongst many other things) uses now proper theories for the main planets and moons. The positions and orientations are now mostly correct and accurate :)
