### ISSUE TITLE
Build instructions out of date

### ISSUE THREAD

**Issue by Sw1fty** [cosmonium/cosmonium#14]
Hi,

The setup and build instructions are out of date now that the space engine is in C++

Please can you update so I can have a crack at adding to this project.

Many Thanks

**Comment by el-dee** [comment]
Hi!

The documentation update is ongoing (it's one of my last remaining tasks before doing a new release), I will focus on the build instructions and the required dependencies and tools.

For the record, most of the engine is still in Python, and there is a fallback Python implementation of the C++ engine that is automatically loaded if the C++ engine can not be loaded (Of course it is much more slower and the orbit and rotation models are not as accurate)

**Comment by el-dee** [comment]
I made a first version of the build instructions, you can find them on the Wiki https://github.com/cosmonium/cosmonium/wiki/Build

Please reopen this issue if there are any missing or wrong informations ! Sometimes, hidden dependencies are missed.
