### ISSUE TITLE
Error loading shuttle_controls.egg

### ISSUE THREAD

**Issue by Epihaius** [cosmonium/cosmonium#15]
After installing the application using `cosmonium-0.2.0_win_amd64.exe`, it crashes each time I try to open an editor window (e.g. `Preferences`), with the following error:

`:loader(error): Couldn't load file shuttle_controls.egg: not found on model path (currently: "/d/cosmonium;/..;/../models")`

OS: Windows 10

**Comment by el-dee** [comment]
The model file is shipped with Panda3D but was not included in the binary distribution.

Fixed in 8ea04eaeacb6a48bcd449bdf29018faedc5d51e5

**Comment by Epihaius** [comment]
@el-dee Shouldn't its texture also be added to `cosmonium/models/maps`? Otherwise the model would just look black instead of showing the arrows. It's `models/maps/shuttle_controls_1.rgb` in the Panda installation.

**Comment by el-dee** [comment]
Indeed ! I actually copied the wrong file :( Thanks for your keen eye :)

**Comment by el-dee** [comment]
Properly fixed in 92de1551300a8770c0cd74302a70a4287b20ef49

**Comment by Epihaius** [comment]
Glad I could help :) !

**Comment by el-dee** [comment]
This is fixed in V0.2.1 (https://github.com/cosmonium/cosmonium/releases/tag/v0.2.1)
