### ISSUE TITLE
Error while launching for the first time

### ISSUE THREAD

**Issue by AnDrE1503A** [cosmonium/cosmonium#19]
I get this error and I dunno how to fix it (I'm using Mac). Any suggestion?

_Time Awake Since Boot: 3900 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /private/var/folders/lj/25g414nj4cgdvxm2_cc84frc0000gn/T/AppTranslocation/095FA7D5-0D2B-4B48-BC4A-CCF93BAF34D2/d/cosmonium.app/Contents/Frameworks/libpython3.7.dylib
  Reason: image not found

Binary Images:
       0x1016e0000 -        0x1016e3ff7 + (0.0.0) <F11F8D10-EFED-329B-9BBF-634DB997BC8D> /var/folders/*/cosmonium.app/Contents/MacOS/cosmonium
       0x1016f1000 -        0x101878ff7 +libpython3.7.dylib (0) <E14C33C3-3B7D-3E81-8BF5-FCFDDA90C66F> /var/folders/*/cosmonium.app/Contents/Frameworks/libpython3.7.dylib
       0x1062b9000 -        0x10634af47  dyld (750.6) <1D318D60-C9B0-3511-BE9C-82AFD2EF930D> /usr/lib/dyld
    0x7fff3516c000 -     0x7fff35f2cff2  com.apple.AppKit (6.9 - 1894.60.100) <A64D10A6-FE17-39CE-9392-6615BE54E10E> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff37eb9000 -     0x7fff38338feb  com.apple.CoreFoundation (6.9 - 1677.104) <C0D70026-EDBE-3CBD-B317-367CF4F1C92F> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff6ef91000 -     0x7fff6ef92fff  libSystem.B.dylib (1281.100.1) <0A6C8BA1-30FD-3D10-83FD-FF29E221AFFE> /usr/lib/libSystem.B.dylib
    0x7fff6f277000 -     0x7fff6f2c9fff  libc++.1.dylib (902.1) <59A8239F-C28A-3B59-B8FA-11340DC85EDC> /usr/lib/libc++.1.dylib_

**Comment by el-dee** [comment]
Thank you for reporting it.  I made the 0.2.0 release using Python from Homebrew, and it seems that that Python library depends on an external lib for the internationalization and the packaging tool does not include it :(

A quick workaround is to install libintl from Homebrew, but I will make a proper build ASAP !

**Comment by el-dee** [comment]
I made a dev build that no longer use Homebrew, could you give it a check : 

https://github.com/cosmonium/cosmonium/releases/download/latest-dev-build/cosmonium-0.2.0.dev57_macosx_10_9_x86_64.zip

**Comment by el-dee** [comment]
Should be fixed in V0.2.1 (https://github.com/cosmonium/cosmonium/releases/tag/v0.2.1)
