### ISSUE TITLE
Missing dependency pyyaml

### ISSUE THREAD

**Issue by robinchm** [cosmonium/cosmonium#2]
'pyyaml' should be included in the `requirements.txt`.

**Comment by el-dee** [comment]
PyYAML is included in Cosmonium, but there was a wrongly done import which ignored the local version, this should be fixed in [dev_v0.1.1](https://github.com/cosmonium/cosmonium/tree/dev_v0.1.1) branch

**Comment by robinchm** [comment]
No problem!

**Comment by el-dee** [comment]
I made the dev branch the default one now so that bugfixes are immediately visible when cloning the repo
