### ISSUE TITLE
Please add hashsums for the downloads so that their integrity can be verified (or sign them)

### ISSUE THREAD

**Issue by mYnDstrEAm** [cosmonium/cosmonium#24]
Please add hashsums to the [downloads](https://github.com/cosmonium/cosmonium/wiki/Download).

This would only take a minute or so and is one of the most basic, necessary and easiest steps one can take to ensure integrity of software.

It would be best to sign the hashed downloads with GPG but adding hashsums would be good enough. Some more info [here](https://security.stackexchange.com/questions/240204/how-can-the-authenticity-of-releases-on-github-and-gitlab-be-ensured-can-their).

Note that the hashsum only verifies the integrity of the built binary, not that the built binary matches the public source code of this repository. The next step would be for the package to be reproducible so that when other people build the binary it has the same hashsum.

It is so simple to solve that this short info obtained via `sha512sum ./cosmonium-0.2.1_manylinux1_x86_64.tar.gz` almost closes the issue: `c963a41a94447b756c2f11e0c0bdc9a5ae517e69fdb766db615424c64938d783f138781bca10d44e8a0d685d41c02fbf11568f078b88a631540eae9987447374` for `Linux : cosmonium-0.2.1_linux_x86_64.tar.gz` of the Downloads page.

**Comment by el-dee** [comment]
Thank you for the suggestion, it's indeed pretty easy to do and has a real added value.

I will upload the hashsum of all the released builds, and also add their generation in the build script.

Build repeatability is a tougher thing to do right now, I guess on Linux it's not a problem as the release build is done in a manylinux docker container, so there is full control of the tool chain and all the dependencies. On the other hand on macOS and Windows, there is nothing yet.

**Comment by rdb** [comment]
Creating a reproducible build requires setting the env var PYTHONHASHSEED to 0 and SOURCE_DATE_EPOCH to the UNIX timestamp of the latest commit when building.  Panda 1.10.9 will add some changes to improve build reproducibility.

**Comment by el-dee** [comment]
shasum512 have been added for the latest builds in the release assets and linked in the wiki.

I will revisit this topic and test build reproducibility once Panda3D 1.10.9 is out
