### ISSUE TITLE
Program crashes when I try to use the toolbar while context menu is open

### ISSUE THREAD

**Issue by xandra18** [cosmonium/cosmonium#26]
**Bug Description**
I noticed that whenever I try to click on an option from the toolbar while the context menu is open, the program crashes and instantly closes the window. 

I first found this bug on Ubuntu 20.04.2 LTS, running the latest stable release (0.2.1) . Afterwards I tried it on Windows 10 which wielded the same results, also running the latest stable version.

**How to Reproduce**
1. Open the context menu by right-clicking on any celestial body.
2. Click on any of the toolbar options (e.g. "Select", "Time", etc.).

![screenshot](https://user-images.githubusercontent.com/56251178/130357602-4132c09d-fd4b-46e0-b2ea-bc46b584c7c2.jpg)

**Result**
The program crashes by instantly closing the window.

**Comment by el-dee** [comment]
Fixed by #27
