### ISSUE TITLE
Improve rendering on HiDPI displays

### ISSUE THREAD

**Issue by SevenSpheres** [cosmonium/cosmonium#28]
Some of my old comments here must have come across as somewhat rude, sorry for that.

Looking at Cosmonium again on a HiDPI display, the text appears very small. It would be nice if text appeared similar in size regardless of display size, as in Celestia. (This is an issue in Gaia Sky too...)

![cosmonium](https://user-images.githubusercontent.com/56284207/174898842-be4a16d3-72dd-4ada-b1b6-f9b5d1f8f58d.png)

Also, the background stars appear very faint, almost to the point of being invisible. Is there any way to change this?

**Comment by el-dee** [comment]
Hello and no worries :)

There is already a parameter to scale UI, you can find it in Cosmonium -> Preferences -> Advanced -> Scale UI With that slider you can up scale or downscale the UI independently of the rendering.

Now in the current release I'm improving HiDPI (and HDR) screens support, so I thing I will add a auto-scale mode that will scale the UI depending on the screen DPI (and keep the manual scaling as an option)

Scaling the emissive points is indeed a good idea, I will add it in the next release (I think it's quite trivial to add) I just have to include it properly with HDR and Bloom

**Comment by el-dee** [comment]
Point-like objects scaling and auto-scale according to screen DPI is added and working (Also, labels were not scaled, I fixed that too).

I will make dev builds again soon so it can be used.
