### ISSUE TITLE
Is there a release scheduled soon?

### ISSUE THREAD

**Issue by luzpaz** [cosmonium/cosmonium#30]
Also is it possible to upkeep the changelog when next release occurs ? For example 2.1.1. is not mentioned in the [Changelog](https://github.com/cosmonium/cosmonium/wiki/Changelog).

**Comment by el-dee** [comment]
Indeed a new release is clearly overdue, or at least a new dev snapshot. Working on too any a feature in parallel was not a good idea. I will fix the outstanding bugs and do a new release/snapshot.

I updated the changelog page, V0.2.1.1 was indeed only referenced in the release page.

**Comment by el-dee** [comment]
A new stable snapshot is finally released, see https://github.com/cosmonium/cosmonium/releases/tag/v0.3.0.dev837

I will publish soon a roadmap towards V0.3.0 release, which should be ready in few months
