### ISSUE TITLE
Merge this with Celestia

### ISSUE THREAD

**Issue by SevenSpheres** [cosmonium/cosmonium#4]
@el-dee, please contribute to Celestia instead of making another version of it!

**Comment by SevenSpheres** [comment]
Since Cosmonium is written in Python and Celestia is written in C++, and Cosmonium seems to have no improvements over Celestia except procedural texture generation, I guess this isn't an issue. Keep working on Cosmonium, but please also contribute to Celestia!

**Comment by el-dee** [comment]
You guessed my answer right,  the long term goal of Cosmonium and Celestia are not the same,  for Cosmonium it's the procedural generation of planets, systems,  galaxies and be photorealistic.... 

Also, the core engine is a third-party one, Panda3d, and based on python,  so there is no easy way to merge part of the code.

That said, I was and still am a user of Celestia and I will try to contribute whenever possible. I intend to add to the texture and planet generator a way to export the generated results as Celestia add on.

**Comment by SevenSpheres** [comment]
Photorealism is also a goal of Celestia, and Celestia Origin and Project Echoes greatly improve it. There seems to be some delay getting these addons into the main repository though.
