### ISSUE TITLE
ESC should exit fullscreen

### ISSUE THREAD

**Issue by SevenSpheres** [cosmonium/cosmonium#5]
Well I decided to try Cosmonium anyway, and now I can't get out of full screen mode! Pressing ESC doesn't work, restarting the program doesn't work, _reinstalling_ the program doesn't work! Help please!

**Comment by SevenSpheres** [comment]
I see, it's "Alt-Enter". Please consider making ESC exit fullscreen mode also.

**Comment by el-dee** [comment]
The keyboard shortcuts are not always intuitive,  I will try to find a way to improve that, maybe using escape or displaying a help panel somewhere.

**Comment by el-dee** [comment]
Now a help text is displayed when entering fullscreen and in the Window menu there is also the option to leave fullscreen mode.
