### ISSUE TITLE
Clicking on distant objects doesn't select them

### ISSUE THREAD

**Issue by SevenSpheres** [cosmonium/cosmonium#8]
Clicking on an object that is visible as a point doesn't select it

**Comment by el-dee** [comment]
The underlying engine does not provide a way to know which point is under the mouse,  in the future I will make a pick buffer in opengl to be able to click on any shape. 

The current workaround is to enable labels as they are clickable

**Comment by el-dee** [comment]
Fix is available in the dev builds
